[[fb-uuid]]
= Использование UUID в Firebird
Симонов Денис
v1.0 от 05.06.2026
:doctype: article
:sectnums:
:sectanchors:
:toc: left
:toclevels: 4
:outlinelevels: 6:0
:icons: font
:experimental:
:lang: ru
:imagesdir: images
:toc-title: Содержание
:chapter-label: Глава
:example-caption: Пример
:figure-caption: Рисунок
:table-caption: Таблица
:note-caption: Примечание
:caution-caption: Внимание
:important-caption: Важно
:warning-caption: Предупреждение
:version-label: Версия
:source-highlighter: coderay
ifdef::backend-pdf[]
:pdf-fontsdir: theme/fonts
:pdf-themesdir: theme/firebird-pdf
:pdf-theme: firebird
:source-highlighter: pygments
endif::[]
ifdef::backend-html5[]
:stylesdir: theme/firebird-html
:stylesheet: firebird.css
:source-highlighter: highlight.js
endif::[]

[dedication%notitle]
--
Этот материал был создан при поддержке и спонсорстве компании https://www.ibase.ru[iBase.ru], которая разрабатывает  инструменты Firebird SQL для предприятий и предоставляет сервис технической поддержки для Firebird SQL.

Материал выпущен под лицензией Public Documentation License https://www.firebirdsql.org/file/documentation/html/en/licenses/pdl/public-documentation-license.html
--

toc::[]

[preface]
== Предисловие

Некоторые пользователи Firebird высказывают пожелания, чтобы в Firebird добавили новый тип данных `UUID` по аналогии с PostgreSQL. Что же давай те разберёмся что такое UUID, как с ним работать в Firebird и нужен ли для этого отдельный тип данны.

== Что такое UUID?

UUID (Universally Unique Identifiers) -- это универсальный уникальный идентификатор, который определён в https://datatracker.ietf.org/doc/html/rfc9562[RFC 9562], ISO/IEC 9834-8:2005 и связанных стандартах. (В некоторых системах это называется GUID, глобальным уникальным идентификатором.) Этот идентификатор представляет собой 128-битное значение, генерируемое специальным алгоритмом, практически гарантирующим, что этим же алгоритмом оно не будет получено больше нигде в мире. Таким образом, эти идентификаторы будут уникальными и в распределённых системах, а не только в единственной базе данных, как значения генераторов последовательностей.

== Как хранить UUID?

Как было сказано выше UUID представляет собой 128-битное уникальное значение, таким образом для его хранения требуется 16-байт. В Firebird нет специального типа данных для хранения UUID, но его можно сохранить просто как набор байт в типе данных `BINARY(16)`. Если вы хотите, чтобы определение ваших таблиц было похоже на PostgreSQL, то просто создайте домен с именем `UUID`.

[source,sql]
----
CREATE DOMAIN UUID AS BINARY(16);
----

[NOTE]
====
В Firebird до версии 4.0 не было специального типа `BINARY` для хранения бинарных данных, тем не менее вы могли хранить бинарные данные ограниченной длины в типе `CHAR(N)` с набором символом `OCTETS`. Таким образом, в предыдущих версиях домен `UUID` должен быть объявлен так:

[source,sql]
----
CREATE DOMAIN UUID AS CHAR(16) CHARACTER SET OCTETS;
----
====

Теперь вы можете использовать домен `UUID` как тип данных для уникальных идентификаторов:

[source,sql]
----
CREATE TABLE T (
   ID UUID NOT NULL,
   NAME VARCHAR(30) NOT NULL,
   ...
   CONSTRAINT PK_T_ID PRIMARY KEY (ID)
);
----

== Генерация UUID

RFC 9562 определяет несколько версий UUID. Каждая версия имеет свои требования к генерации новых значений UUID и имеет свои преимущества и недостатки. Значение UUID может быть генерировано как на стороне приложения, так и на стороне СУБД.

В Firebird имеется встроенная функция `GEN_UUID()`, которая генерирует UUID версии 4.

[NOTE]
====
В Firebird 6.0 функция `GEN_UUID()` может принимать параметр, в который передаётся версия алгоритма генерации UUID. Допустимыми значениями версии являются 4 и 7. Если значение аргумента не задано, то генерируется UUID версии 4.
====

Добавление новой записи в таблицу с использованием функции `GEN_UUID()` будет выглядеть следующим образом:

[source,sql]
----
INSERT INTO T (ID, NAME, ...)
VALUES (GEN_UUID(), ?, ...)
RETURNING ID
----

Если вы не хотите каждый раз писать `GEN_UUID()` в ваших запросах, то можно создать `BEFORE INSERT` триггер, в котором будет заполняться значение поля `ID`, если оно не задано в запросе.

[source,sql]
----
CREATE OR ALTER TRIGGER TR_T_BI FOR T
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_UUID();
END
----

[IMPORTANT]
====
К сожалению указание функции `GEN_UUID()` в качестве значения по умолчанию для поля `ID` не допускается.
====

== Отображение UUID в человеко-читаемой форме

Функция `GEN_UUID()` возвращает универсальный уникальный идентификатор (UUID) в виде 16-байтовой двоичной строки. Отображение такого идентификатора в человеко-читаемой форме можно возложить на клиентское приложение, но если необходимо преобразовать UUID в символьную строку, то для это в Firebird существует функция `UUID_TO_CHAR()`.

Примеры использования `UUID_TO_CHAR()`:

[source,sql]
----
select uuid_to_char(gen_uuid()) from rdb$database;
-- A4D82B77-BFF8-4D05-BF28-16A24B6ACE2C

select uuid_to_char(id) as s_uuid from t;
-- A4D82B77-BFF8-4D05-BF28-16A24B6ACE2C
----

Также существует обратная функция `CHAR_TO_UUID()`, которая преобразует читабельную 36-ти символьную символику
UUID к соответствующему 16-ти байтовому значению UUID.

[source,sql]
----
SELECT CHAR_TO_UUID('A0bF4E45-3029-2a44-D493-4998c9b439A3') FROM rdb$database;
----

== Заключение

Firebird позволяет работать с универсальными уникальными идентификаторами (UUID), добавлять новый тип в ядро Firebird не требуется. Для хранения UUID используйте тип данных `BINARY(16)`. Вы можете создать домен с именем `UUID` и использовать его при определении столбцов таблиц или параметров хранимых процедур. UUID может быть генерирован как на стороне приложения, так и на сервере Firebird. Для генерации UUID на стороне Firebird используется функция `GEN_UUID()`, которая генерирует UUID версии 4. Для преобразования UUID в человеко-читаемую форму вы можете воспользоваться встроенной функцией `UUID_TO_CHAR()`. Для преобразования UUID из символьной формы в бинарную вы можете воспользоваться функцией `CHAR_TO_UUID()`.
